apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: front
  name: front
spec:
  type: LoadBalancer
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    io.kompose.service: front
status:
  loadBalancer: {}
