apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  template:
    metadata:
      labels:
        io.kompose.service: front
        io.kompose.network/myapp: "true"
    spec:
      containers:
      - image: vikagumi/quotes-front:v1
        name: front
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
